# Generated by Django 4.1.7 on 2023-06-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_desciption_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
