# Generated by Django 4.1.7 on 2023-06-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
